#include <dcgn/asyncRecv.cu>
#include <dcgn/asyncSend.cu>
#include <dcgn/asyncTest.cu>
#include <dcgn/asyncWait.cu>
#include <dcgn/barrier.cu>
#include <dcgn/broadcast.cu>
#include <dcgn/free.cu>
#include <dcgn/getAsyncRequest.cu>
#include <dcgn/getCPUID.cu>
#include <dcgn/getGPUID.cu>
#include <dcgn/getRank.cu>
#include <dcgn/getRequest.cu>
#include <dcgn/getSize.cu>
#include <dcgn/gpuOutput.cu>
#include <dcgn/init.cu>
#include <dcgn/malloc.cu>
#include <dcgn/recv.cu>
#include <dcgn/send.cu>
#include <dcgn/sendRecvReplace.cu>
#include <dcgn/OutputStream.cu>
